### ISSUE TITLE
i am getting an error in file whisper.worker.js

### ISSUE THREAD

**Issue by Awezsk** [jamezmca/free-scribe#1]
Unexpected token '<', "<!doctype "... is not valid JSON

on whisper worker js  line 33
![Uploading Screenshot (58).png…]()

**Comment by jamezmca** [comment]
Can you please try replacing all the code in your current whisper.worker with the version in the GitHub and let me know if it works?

**Comment by jatiwalnikhil61** [comment]
Hello. I am also getting the same error even after replacing the whisper.worker code with the github version. If you could please address it, it would be a big help

**Comment by jatiwalnikhil61** [comment]
I closed my system and restarted the server. It is working right now. Thank you. @Awezsk you should also try it once

**Comment by Belsinghferrus** [comment]
![Screenshot 2024-07-20 104123](https://github.com/user-attachments/assets/9436ac05-e3e5-4435-be10-3dfc2bc54198)

@jamezmca I have tried replacing my code with GitHub code.. 
`Unexpected token '<', "<!doctype "... is not valid JSON`
Still the error is not resolved..

And also I have another error in place 
```
whisper.worker.js:83 Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'model')
    at new GenerationTracker (whisper.worker.js:83:100)
    at transcribe (whisper.worker.js:40:31)
    at async whisper.worker.js:21:9
GenerationTracker	@	whisper.worker.js:83
transcribe	@	whisper.worker.js:40
```


NOTE: Getting this error even in incognito

**Comment by KevinBermudezC** [comment]
I have the same error :(

**Comment by Belsinghferrus** [comment]
I think cache is causing this issue... Try it in Firefox or incognito or other browser.. It worked for me..

**Comment by KevinBermudezC** [comment]
After I Commented here, it works lmao, I just got one thing, 
![image](https://github.com/user-attachments/assets/d15e9c07-68a7-4226-af57-c6799cd9728c)
Not sure why sometimes when i record my voice or upload a mp3 it says that

**Comment by Madhesh21** [comment]
@Belsinghferrus  add this code on top 

import {pipeline, env} from '@xenova/transformers`;
import { MessageTypes } from './presets'
env.allowLocalModels = false;

after this , shutdown your localhost and clear browser cache and then restart your browser and your localhost.

I hope this solves your problem

**Comment by rakshitgupta23** [comment]
I have tried everything but it's still not working
Earlier i was getting these errors

![Screenshot 2024-09-06 195046](https://github.com/user-attachments/assets/92a63742-ba7f-485f-9780-6934c08ac08d)
But after incorporating @Madhesh21 suggestion
import {pipeline, env} from '@xenova/transformers`;
import { MessageTypes } from './presets'
env.allowLocalModels = false;
I am getting this error
![Screenshot 2024-09-06 195258](https://github.com/user-attachments/assets/e67105d9-3ef3-42bd-bf3c-50f5b54a9593)

After adding one more line:-
env.useBrowserCache = false; 
on @ynamite 's suggestion now it is working on Microsoft Edge, but still not working on Google Chrome(Incognito or Normal window)

**Comment by Belsinghferrus** [comment]
I would say if it's already working on Edge..you might as well continue finishing it in edge.. 

I faced the same issue with chrome, Thanks to Edge.

**Comment by rakshitgupta23** [comment]
@Belsinghferrus Surprisingly, it is now working in chrome. But now translation is not working, its running endlessly.

**Comment by rakshitgupta23** [comment]
Now getting issue with translation part. The loading just goes on endlessly. @jamezmca

**Comment by Lakshya291** [comment]
I have a question,
why did we declare model if we are not using this while initializing the instance and passing null in the pipeline?
    static model = 'openai/whisper-tiny.en'
    
    this.instance = await pipeline(this.task, null, { progress_callback })

**Comment by jaekookang** [comment]
> I have a question, why did we declare model if we are not using this while initializing the instance and passing null in the pipeline? static model = 'openai/whisper-tiny.en'
> 
> ```
> this.instance = await pipeline(this.task, null, { progress_callback })
> ```

I don't know why, but I've tried replacing `null` to `this.model`, which didn't work. 'openai/whisper-tiny.en' seems not supported anymore. Instead, I tried 'Xenova/whisper-tiny.en' and it worked. 

I think you can simply ignore it because it will automatically be downloaded anyway.

**Comment by Imanuelchibuzor** [comment]
> > I have a question, why did we declare model if we are not using this while initializing the instance and passing null in the pipeline? static model = 'openai/whisper-tiny.en'
> > ```
> > this.instance = await pipeline(this.task, null, { progress_callback })
> > ```
> 
> I don't know why, but I've tried replacing `null` to `this.model`, which didn't work. 'openai/whisper-tiny.en' seems not supported anymore. Instead, I tried 'Xenova/whisper-tiny.en' and it worked.
> 
> I think you can simply ignore it because it will automatically be downloaded anyway.

@jaekookang kindly share a copy of your whisper.worker.js file so I can compare with mine.
Thank you

**Comment by jaekookang** [comment]
> > > I have a question, why did we declare model if we are not using this while initializing the instance and passing null in the pipeline? static model = 'openai/whisper-tiny.en'
> > > ```
> > > this.instance = await pipeline(this.task, null, { progress_callback })
> > > ```
> > 
> > 
> > I don't know why, but I've tried replacing `null` to `this.model`, which didn't work. 'openai/whisper-tiny.en' seems not supported anymore. Instead, I tried 'Xenova/whisper-tiny.en' and it worked.
> > I think you can simply ignore it because it will automatically be downloaded anyway.
> 
> @jaekookang kindly share a copy of your whisper.worker.js file so I can compare with mine. Thank you

@Imanuelchibuzor  No problem. Here is the full code of my `whisper.worker.js` file because I can't directly attach .js file here.

```
import { pipeline, env } from "@xenova/transformers";
// import { pipeline, env } from "@huggingface/transformers";
import { MessageTypes } from "./presets";
env.allowLocalModels = false;
env.useBrowserCache = true;

class MyTranscriptionPipeline {
    static task = "automatic-speech-recognition";
    // static model = "openai/whisper-tiny.en";
    // static model = "Xenova/whisper-tiny.en";
    static model = "Xenova/whisper-small.en";
    static instance = null;

    static async getInstance(progress_callback = null) {
        if (this.instance === null) {
            this.instance = await pipeline(this.task, this.model, {
                progress_callback
            })
        }
        return this.instance;
    }
}

self.addEventListener("message", async (event) => {
    const { type, audio } = event.data;
    if (type === MessageTypes.INFERENCE_REQUEST) {
        await transcribe(audio)
    }
})

    /**
     * Transcribes an audio buffer using the Whisper ASR model.
     *
     * The provided audio buffer is processed in chunks, and the generated
     * text is sent back to the main thread as it is generated.
     *
     * The function takes an audio buffer as input, and returns a Promise that
     * resolves when the transcription is complete.
     *
     * @param {AudioBuffer} audio - The audio buffer to transcribe.
     *
     * @returns {Promise<void>}
     */
async function transcribe(audio) {
    sendLoadingMessage("loading");

    let pipeline;

    try {
        pipeline = await MyTranscriptionPipeline.getInstance(load_model_callback);
    } catch (err) {
        console.log(err)
        console.log(err.message)
    }

    sendLoadingMessage("success");

    const stride_length_s = 5;
    const generationTracker = new GenerationTracker(pipeline, stride_length_s);
    await pipeline(audio, {
        top_k: 0,
        do_sample: false,
        chunk_length: 30,
        stride_length_s: stride_length_s,
        return_timestamps: true,
        callback_function: generationTracker.callbackFunction.bind(generationTracker),
        chunk_callback: generationTracker.chunkCallback.bind(generationTracker),
    })
    generationTracker.sendFinalResult();
}

async function load_model_callback(data) {
    const { status } = data;
    if (status === "progress") {
        const { file, progress, loaded, total } = data;
        sendDownloadingMessage(file, progress, loaded, total);
    }
}

function sendLoadingMessage(status) {
    self.postMessage({
        type: MessageTypes.LOADING,
        status
    })
}

async function sendDownloadingMessage(file, progress, loaded, total) {
    self.postMessage({
        type: MessageTypes.DOWNLOADING,
        file,
        progress,
        loaded,
        total,
    })
}

class GenerationTracker {
/**
 * Constructs a GenerationTracker instance.
 *
 * @param {Object} pipeline - The transcription pipeline used for processing audio data.
 * @param {number} stride_length_s - The length of the stride in seconds for processing audio chunks.
 *
 * Initializes the pipeline, stride length, and other properties like chunk, time_precision,
 * processed_chunks, and callbackFunctionCounter. The time_precision is calculated based on
 * the feature extractor and model configuration within the pipeline.
 */
    constructor(pipeline, stride_length_s) {
        console.log("pipeline:", pipeline);
        console.log("pipeline.model:", pipeline.model);
        console.log("pipeline.model.config:", pipeline.model && pipeline.model.config);
        this.pipeline = pipeline;
        this.stride_length_s = stride_length_s;
        this.chunks = [];
        this.time_precision = pipeline?.processor.feature_extractor.config.chunk_length / pipeline.model.config.max_source_prositions;
        this.processed_chunks = [];
        this.callbackFunctionCounter = 0;
    }

    sendFinalResult() {
        self.postMessage({ type: MessageTypes.INFERENCE_DONE });
    }

    /**
     * Processes a set of beams returned by the transcription pipeline and sends a partial recognition result.
     *
     * The callback function is called by the transcription pipeline for every new set of beams generated during
     * the audio processing. This function is responsible for extracting the speech recognition output from the
     * best beam and sending a partial recognition result to the main thread.
     *
     * @param {Array} beams - A list of beams returned by the transcription pipeline.
     */
    callbackFunction(beams) {
        this.callbackFunctionCounter += 1;
        if (this.callbackFunctionCounter % 10 !== 0) {
            return
        }

        // Get the speech-recognition output
        const bestBeam = beams[0];
        let text = this.pipeline.tokenizer.decode(bestBeam.output_token_ids, {
            skip_special_tokens: true
        })

        const result = {
            text,
            start: this.getlastChunkTimestamp(),
            end: undefined,
        }

        createPartialResultMessage(result);
    }

    chunkCallback(data) {
        this.chunks.push(data)
        // eslint-disable-next-line no-unused-vars
        const [ text, {chunks}] = this.pipeline.tokenizer._decode_asr(
            this.chunks, 
            {
                time_precision: this.time_precision,
                return_timestamps: true,
                force_full_sequence: false,
            }
        );

        this.processed_chunks = chunks.map((chunk, index) => {
            return this.processChunk(chunk, index)
        });

        createResultMessage(
            this.processed_chunks, false, this.getlastChunkTimestamp()
        );
    };

    getlastChunkTimestamp(){
        if (this.processed_chunks.length=== 0) {
            return 0;
        }
    }

    processChunk(chunk, index) {
        const {text, timestamp} = chunk;
        const [start, end] = timestamp;

        return {
            index,
            text: `${text.trim()}`,
            start: Math.round(start),
            end: Math.round(end) || Math.round(start + 0.9 * this.stride_length_s )
        }
        
    }
};

function createResultMessage(results, isDone, completedUntilTimestamp) {
    self.postMessage({
        type: MessageTypes.RESULT,
        results,
        isDone,
        completedUntilTimestamp
    });
};

function createPartialResultMessage(result) {
    self.postMessage({
        type: MessageTypes.RESULT_PARTIAL,
        result
    });
};


```

**Comment by Imanuelchibuzor** [comment]
Thank you so much
