### ISSUE TITLE
please help: transcribe only works in private window in chrome

### ISSUE THREAD

**Issue by ynamite** [jamezmca/free-scribe#3]
For some reason, transcribing only works in an incognito window.
Even with the following added to the whisper.worker.js, it does not work in a normal window:
```
import { pipeline, env } from '@xenova/transformers';
import { MessageTypes } from './presets';
env.allowLocalModels = false;
```

In a normal window/tab I get the following error:
```
Downloading...
whisper.worker.js:34 SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at getModelJSON (http://localhost:5173/node_modules/.vite/deps/@xenova_transformers.js?v=d6048e6e:14328:15)
    at async Promise.all (index 0)
    at async loadTokenizer (http://localhost:5173/node_modules/.vite/deps/@xenova_transformers.js?v=d6048e6e:17831:16)
    at async AutoTokenizer.from_pretrained (http://localhost:5173/node_modules/.vite/deps/@xenova_transformers.js?v=d6048e6e:21018:46)
    at async Promise.all (index 0)
    at async loadItems (http://localhost:5173/node_modules/.vite/deps/@xenova_transformers.js?v=d6048e6e:29508:3)
    at async pipeline (http://localhost:5173/node_modules/.vite/deps/@xenova_transformers.js?v=d6048e6e:29469:19)
    at async MyTranscriptionPipeline.getInstance (http://localhost:5173/src/utils/whisper.worker.js?worker_file&type=module:13:29)
    at async transcribe (http://localhost:5173/src/utils/whisper.worker.js?worker_file&type=module:33:20)
App.jsx:37 Downloading...
whisper.worker.js:85 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'model')
    at new GenerationTracker (whisper.worker.js:85:22)
    at transcribe (whisper.worker.js:39:31)
    at async whisper.worker.js:23:9
```

**Comment by ynamite** [comment]
A workaround seems to be to add the following to the worker JS files. Suboptimal, since it circumvents the caching of the model, but it works in normal browser window:
```
import { pipeline, env } from '@xenova/transformers';
env.allowLocalModels = false;
env.useBrowserCache = false;
```

edit: this is a known issue with transformers.js and might be fixed in the next version / near future.

**Comment by AdvayDhar** [comment]
This issue of cache disrupting workflow in normal tabs is still not fixed.
